"""create_claims_and_status_history

Revision ID: 0dc3f8cd4596
Revises: 006582aaca9e
Create Date: 2026-09-21 14:11:23.531655
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '0dc3f8cd4596'
down_revision: str | None = '006582aaca9e'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claimant_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('claim_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('claimed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('incident_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'in_review', 'approved', 'rejected', 'settled', 'closed', name='claimstatus'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['claimant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_assigned_to'), 'claims', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_claims_claimant_id'), 'claims', ['claimant_id'], unique=False)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_index('ix_claims_status_claimant', 'claims', ['status', 'claimant_id'], unique=False)
    op.create_table('claim_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('draft', 'submitted', 'in_review', 'approved', 'rejected', 'settled', 'closed', name='claimstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('draft', 'submitted', 'in_review', 'approved', 'rejected', 'settled', 'closed', name='claimstatus'), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_status_history_claim_id'), 'claim_status_history', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_status_history_claim_id'), table_name='claim_status_history')
    op.drop_table('claim_status_history')
    op.drop_index('ix_claims_status_claimant', table_name='claims')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_claimant_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_assigned_to'), table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
