"""create reviews table

Revision ID: 98e2cd887f94
Revises: 0dc3f8cd4596
Create Date: 2026-09-22 09:33:23.714974
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '98e2cd887f94'
down_revision: str | None = '0dc3f8cd4596'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('approve', 'reject', 'request_info', name='reviewdecision'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_reviews_claim_id'), 'claim_reviews', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_reviews_claim_id'), table_name='claim_reviews')
    op.drop_table('claim_reviews')
    # ### end Alembic commands ###
