"""create documents table

Revision ID: 0ffe8a1920cf
Revises: 98e2cd887f94
Create Date: 2026-09-22 09:40:12.986026
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '0ffe8a1920cf'
down_revision: str | None = '98e2cd887f94'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_documents_claim_id'), 'claim_documents', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_documents_claim_id'), table_name='claim_documents')
    op.drop_table('claim_documents')
    # ### end Alembic commands ###
